### ISSUE TITLE
Cannot build on Mac OS - 'sys/vmmeter.h' file not found

### ISSUE THREAD

**Issue by samphilipd** [monero-project/monero-gui#1120]
I get the following error trying to build on Mac OS High Sierra (10.13.3)

```
monero-gui/monero/external/unbound/compat/getentropy_osx.c:47:10: fatal error: 'sys/vmmeter.h' file not found
```

Any ideas? I've installed all the dependencies listed in the README.

**Comment by skftn** [comment]
Could you try again using latest master and see if you get the same error?

**Comment by xmrdsc** [comment]
+invalid
